added wb6-nousbhub overlay
contactless/wb-dt-overlays pull request #5
Opened 2022-04-06 13:21 UTC by vdromanov

погонял на железе - всё работает хорошо

2022-04-06 13:23 UTC, vdromanov commented on debian/changelog
> + -- Vladimir Romanov <v.romanov@wirenboard.ru>  Mon, 21 Feb 2022 10:27:12 +0300
чейнджлог руками писал - очепятка
про dch - знаю

2022-04-07 16:54 UTC, evgeny-boger requested changes
что-то я ничего не понял.

То есть wb-gsm будет брать параметры из отключённой ноды что ли? Какая-то ерунда.

2022-04-07 22:49 UTC, vdromanov commented
> что-то я ничего не понял.
> 
> То есть wb-gsm будет брать параметры из отключённой ноды что ли? Какая-то ерунда.

`wb-gsm` смотрит в старую ноду (на отключенном usb-хабе; через alias) и берет оттуда gpio и status. Status этой ноды меняется только hwconf'ом в wbc-модулях. Т.е. хаб отключен (чтоб не матчился); статус модемной ноды - ок => wb-gsm видит, что модем выставили в webui и работает дальше

`wb-gsm` понимает, что usb-порт - с модемом по наличию `compatible = "wirenboard,wbc-usb"` на нём => в оверлее compatible просто переезжает, куда надо (в загруженном dtb сильно не разгуляешься)

Можно сделать и по-другому (но по-моему, всё - хуже):

- не отключать usb-хаб => Будут спецэффекты, если vid/pid модема совпадут с vid/pid хаба
- сделать честную новую ноду модема с gpio, статусом, ... на новом usb-порту => Много копипаста; сломается hwconf (там-то всё на на старую ноду завязано, которую никуда не деть)
- прописать gpio, power_type, ... модема куда-то отдельно, и потом подсовывать их в ноду модема => изменения, как минимум, в wb-gsm

А чем плох реализованный подход?

2022-04-14 20:19 UTC, closed without merging

2022-04-14 20:20 UTC, vdromanov commented
Обсуждали - решили сделать отдельной dts